#ifndef STM32_CONFIG_H
#define STM32_CONFIG_H

#include "main.h"

#ifdef DEBUG
#include <stdio.h>
#define DEBUG_PRINTF(...) printf(__VA_ARGS__)
#else
#define DEBUG_PRINTF(...)
#endif

#define AUDIO_I2C_HANDLE hi2c1
#define AUDIO_I2S_HANDLE hi2s1
#define IMU_I2C_HANDLE hi2c1
#define BATT_I2C_HANDLE hi2c1
#define MODEM_UART_HANDLE huart1
// #define DEBUG_UART_HANDLE huart3
#define DISPLAY_PWM_TIMER htim2


#define MCP73871_STAT1_PORT MCP_STAT1_GPIO_Port
#define MCP73871_STAT1_PIN MCP_STAT1_Pin
#define MCP73871_STAT2_PORT MCP_STAT2_GPIO_Port
#define MCP73871_STAT2_PIN MCP_STAT2_Pin
#define MCP73871_PG_PORT MCP_PG_GPIO_Port
#define MCP73871_PG_PIN MCP_PG_Pin

#define MODEM_POWER_PORT MOB_PWR_GPIO_Port
#define MODEM_POWER_PIN MOB_PWR_Pin

#define DRV2603_ENABLE_PORT VIB_EN_GPIO_Port
#define DRV2603_ENABLE_PIN VIB_EN_Pin
#define DRV2603_PWM_PORT VIB_PWM_GPIO_Port
#define DRV2603_PWM_PIN VIB_PWM_Pin

#define AUDIO_SW_PORT AUDIO_SW_GPIO_Port
#define AUDIO_SW_PIN AUDIO_SW_Pin
#define MODEM_RI_Pin UART_RI_Pin
#define MODEM_RI_PORT UART_RI_GPIO_Port


#endif