/**
 * @file input.h
 * @brief Input event definitions
 * @ingroup ui_input
 *
 * Defines all possible input events from the keypad and other
 * input sources throughout the system.
 */

#ifndef INPUT_H
#define INPUT_H

/**
 * @brief Input event enumeration
 * @ingroup ui_input
 *
 * All possible input events that can be generated by the system.
 */
typedef enum
{
    INPUT_KEYPAD_0,    /**< Keypad button 0 */
    INPUT_KEYPAD_1,    /**< Keypad button 1 */
    INPUT_KEYPAD_2,    /**< Keypad button 2 */
    INPUT_KEYPAD_3,    /**< Keypad button 3 */
    INPUT_KEYPAD_4,    /**< Keypad button 4 */
    INPUT_KEYPAD_5,    /**< Keypad button 5 */
    INPUT_KEYPAD_6,    /**< Keypad button 6 */
    INPUT_KEYPAD_7,    /**< Keypad button 7 */
    INPUT_KEYPAD_8,    /**< Keypad button 8 */
    INPUT_KEYPAD_9,    /**< Keypad button 9 */
    INPUT_KEYPAD_STAR, /**< Keypad * button */
    INPUT_KEYPAD_HASH, /**< Keypad # button */
    INPUT_DPAD_UP,     /**< D-pad up */
    INPUT_DPAD_DOWN,   /**< D-pad down */
    INPUT_DPAD_LEFT,   /**< D-pad left */
    INPUT_DPAD_RIGHT,  /**< D-pad right */
    INPUT_SELECT,      /**< Select/OK button */
    INPUT_LEFT,        /**< Left soft key */
    INPUT_RIGHT,       /**< Right soft key */
    INPUT_PICKUP,      /**< Call pickup button */
    INPUT_HANGUP,      /**< Call hangup button */
    INPUT_VOLUME_UP,   /**< Volume up button */
    INPUT_VOLUME_DOWN, /**< Volume down button */
    INPUT_POWER,       /**< Power button */
    INPUT_NONE         /**< No input event */
} input_event_t;

#endif
